[theme]
primaryColor = "#ff6b6b"
backgroundColor = "#1e3c72"
secondaryBackgroundColor = "#2a5298"
textColor = "#ffffff"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[logger]
level = "info"